export default {
  LOGIN: 'تسجيل الدخول',
  DONT_HAVE_ACCOUNT: 'ليس لديك حساب؟',
  REGISTER: 'تسجيل',
  EMAIL: 'البريد الإلكتروني',
  ENTER_YOUR_EMAIL: 'أدخل بريدك الإلكتروني',
  PASSWORD: 'كلمة المرور',
  ENTER_YOUR_PASSWORD: 'أدخل كلمة المرور الخاصة بك',
  FORGOT_PASSWORD: 'نسيت كلمة المرور',
  WELCOME_BACK: 'مرحباً بعودتك',
  LOGIN_WITH_YOUR_DETAILS: 'سجّل دخولك باستخدام بياناتك',
  TODAYS_TRIP_LIST: 'قائمة رحلات اليوم',
  START_TRIP: 'ابدأ الرحلة',
  OPEN: 'فتح',
  NAVIGATE: 'توجيه',
  PICKUP_DETAILS: 'تفاصيل الاستلام',
  DATE: 'التاريخ',
  SELECT_DATE: 'اختر التاريخ',
  TIME: 'الوقت',
  SELECT_TIME: 'اختر الوقت',
  OIL_COLLECTED: 'تم جمع الزيت',
  TYPE_HERE: 'اكتب هنا',
  SIGNATURE: 'التوقيع',
  SIGNATURE_HERE: 'وقّع هنا',
  UPLOAD_IMAGES: 'رفع الصور',
  CAPTURE_UPLOAD_IMAGES: 'التقاط / رفع الصور',
  TAKE_IMAGES_WITH_LIGHT: 'التقط الصور في الضوء لتكون واضحة للرؤية.',
  COLLECTED_SAMPLE_FOR_OIL: 'تم جمع عينة لاختبار الزيت',
  PICKUP_SCREEN: 'شاشة الاستلام',
  PICKUP: 'الاستلام',
  PLEASE_COLLECT_OIL_SAMPLE: 'يرجى جمع عينة الزيت',
  SCHEDULED_TIME: 'الوقت المجدول',
  EXPECTED_OIL_VOLUME: 'الحجم المتوقع للزيت',
  END_TRIP: 'إنهاء الرحلة',
  TOTAL_OIL_PICKUPS: 'إجمالي عمليات استلام الزيت',
  TOTAL_NUMBER_OIL_CANS: 'إجمالي عدد عبوات الزيت',
  MANAGER_NAME: 'اسم المدير',
  NO_IMAGES: 'اختر الصور',
  TOTAL_NUMBER_OF_OIL_VOLUME: 'إجمالي حجم الزيت',
  THIS_IS_REQUIRED: 'هذا مطلوب',
  PROFILE_INFORMATION: 'معلومات الملف الشخصي',
  CHANGE_PASSWORD: 'تغيير كلمة المرور',
  CHANGE_LANGUAGE: 'تغيير اللغة',
  HELP: 'مساعدة',
  TERMS_N_CONDITIONS: 'الشروط والأحكام',
  LOGOUT: 'تسجيل الخروج',
  NO_SCHEDULED_ITEMS_FOUND: 'لم يتم العثور على رحلات مجدولة',
  SAVE: 'حفظ',
  BACK_N_CANCEL: 'الرجوع وإلغاء',
  GO_BACK: 'ارجع',
  VIEW_DETAIL: 'عرض التفاصيل',
  CURRENT_PASSWORD: 'كلمة المرور الحالية',
  ENTER_YOUR_CURRENT_PASSWORD: 'أدخل كلمة المرور الحالية الخاصة بك',
  NEW_PASSWORD: 'كلمة مرور جديدة',
  ENTER_NEW_PASSWORD: 'أدخل كلمة مرور جديدة',
  'RE-TYPE_NEW_PASSWORD': 'أعد إدخال كلمة المرور الجديدة',
  'RE-TYPE_NEW_PASSWORD_AGAIN': 'أدخل كلمة المرور الجديدة مرة أخرى',
  ENTER_YOUR_NEW_PASSWORD: 'أدخل كلمة المرور الجديدة الخاصة بك',
  NAME: 'الاسم',
  WHATSAPP: 'واتساب',
  SAVE_CHANGES: 'احفظ التغييرات',
  ALL_TRIP: 'كل الرحلة',

  ENTER_YOUR_WHATSAPP: 'أدخل الواتس اب الخاص بك',

  CALCULATING_DISTANCE: 'جارٍ حساب المسافة',
  FETCHING_ROUTE: 'جارٍ جلب المسار',
  NO_INCOMPLETE_TRIPS: 'لم يتم العثور على رحلات غير مكتملة',
  ALL_TRIPS_ARE_IN_PROGRESS: 'جميع الرحلات قيد التنفيذ',

  INCOMPLETE: 'غير مكتمل',
  ICOMPLETE: 'مكتمل',
  IN_PROGRESS: 'قيد التنفيذ',
  PRESS_TO_OPEN_CANVAS: 'اضغط لفتح لوحة التوقيع',
  PROCESSING: 'جارٍ المعالجة...',
  CLEAR: 'مسح',

  CONTINUE: 'يكمل',
  CLOSE: 'يغلق',
  COMPLETE: 'مكتمل',

  NO_TRIP_PICKUP_FOUND: 'لم يتم العثور على رحلة التقاط',

  LITRE: 'لتر',

  DAILY: 'يومي',
  WEEKLY: 'أسبوعي',
  URGENT: 'عاجل',
  WEEKLY_TRIP_LIST: 'قائمة الرحلات الأسبوعية',

  NAVIGATE_ALL: 'التنقل إلى الكل',
  DROP_OFF_OIL_CAN: 'إسقاط علبة الزيت',
  CANCEL_TRIP: 'إلغاء الرحلة',
  SEARCH_SCHEDULES: 'البحث في الجداول',

  FUTUTRE_PICKUPS: 'بيك اب المستقبل',

  TODAY: 'اليوم',

  INVALID_EMAIL_ADDRESS: "عنوان بريد إلكتروني غير صالح",

  CAPTURE: "Capture",
  UPLOAD: "Upload",

  "UPLOAD_IMAGE_VIDEO": "تحميل صورة / فيديو",
  "UPLOAD_VIDEO": "تحميل الفيديوهات",
  "CANS": "علب",
  "VIDEO_FRONT_BRANCH_DOOR": "تحميل فيديو لأرضية الفرع الأمامي",
  "ENTER_YOUR_NAME": "ادخل اسمك",
  "NO_BRANCH_NAME": "لا يوجد اسم للفرع"

};
