export default {
  LOGIN: 'لاگ ان کریں',
  DONT_HAVE_ACCOUNT: 'کیا آپ کا اکاؤنٹ نہیں ہے؟',
  REGISTER: 'رجسٹر کریں',
  EMAIL: 'ای میل',
  ENTER_YOUR_EMAIL: 'اپنی ای میل درج کریں',
  PASSWORD: 'پاس ورڈ',
  ENTER_YOUR_PASSWORD: 'اپنا پاس ورڈ درج کریں',
  FORGOT_PASSWORD: 'پاس ورڈ بھول گئے',
  WELCOME_BACK: 'خوش آمدید',
  LOGIN_WITH_YOUR_DETAILS: 'اپنی تفصیلات کے ساتھ لاگ ان کریں',
  TODAYS_TRIP_LIST: 'آج کے دوروں کی فہرست',
  START_TRIP: 'سفر شروع کریں',
  OPEN: 'کھولیں',
  NAVIGATE: 'راستہ دیکھیں',
  PICKUP_DETAILS: 'پک اپ کی تفصیلات',
  DATE: 'تاریخ',
  SELECT_DATE: 'تاریخ منتخب کریں',
  TIME: 'وقت',
  SELECT_TIME: 'وقت منتخب کریں',
  OIL_COLLECTED: 'اکٹھا کیا گیا تیل',
  TYPE_HERE: 'یہاں ٹائپ کریں',
  SIGNATURE: 'دستخط',
  SIGNATURE_HERE: 'یہاں دستخط کریں',
  UPLOAD_IMAGES: 'تصاویر اپ لوڈ کریں',
  CAPTURE_UPLOAD_IMAGES: 'تصاویر کھینچیں / اپ لوڈ کریں',
  TAKE_IMAGES_WITH_LIGHT: 'تصاویر روشنی میں کھینچیں تاکہ واضح نظر آئیں۔',
  COLLECTED_SAMPLE_FOR_OIL: 'تیل کے تجزیہ کے لیے نمونہ لیا گیا',
  PICKUP_SCREEN: 'پک اپ اسکرین',
  PICKUP: 'پک اپ',
  PLEASE_COLLECT_OIL_SAMPLE: 'براہ کرم تیل کا نمونہ اکٹھا کریں',
  SCHEDULED_TIME: 'مقررہ وقت',
  EXPECTED_OIL_VOLUME: 'متوقع تیل کی مقدار',
  END_TRIP: 'سفر ختم کریں',
  TOTAL_OIL_PICKUPS: 'کل تیل کی پک اپس',
  TOTAL_NUMBER_OIL_CANS: 'کل تیل کے ڈبوں کی تعداد',
  MANAGER_NAME: 'مینجر کا نام',
  NO_IMAGES: 'تصاویر منتخب کریں',
  TOTAL_NUMBER_OF_OIL_VOLUME: 'کل تیل کی مقدار',
  THIS_IS_REQUIRED: 'یہ ضروری ہے',
  PROFILE_INFORMATION: 'پروفائل کی معلومات',
  CHANGE_PASSWORD: 'پاس ورڈ تبدیل کریں',
  CHANGE_LANGUAGE: 'زبان تبدیل کریں',
  HELP: 'مدد',
  TERMS_N_CONDITIONS: 'شرائط و ضوابط',
  LOGOUT: 'لاگ آؤٹ',
  NO_SCHEDULED_ITEMS_FOUND: 'کوئی مقررہ سفر نہیں ملا',
  SAVE: 'محفوظ کریں',
  BACK_N_CANCEL: 'واپس جائیں اور منسوخ کریں',
  GO_BACK: 'واپس جائیں',
  VIEW_DETAIL: 'تفصیل دیکھیں',

  CURRENT_PASSWORD: 'موجودہ پاس ورڈ',
  ENTER_YOUR_CURRENT_PASSWORD: 'اپنا موجودہ پاس ورڈ درج کریں',
  NEW_PASSWORD: 'نیا پاس ورڈ',
  ENTER_NEW_PASSWORD: 'نیا پاس ورڈ درج کریں',
  'RE-TYPE_NEW_PASSWORD': 'نیا پاس ورڈ دوبارہ درج کریں',
  'RE-TYPE_NEW_PASSWORD_AGAIN': 'نیا پاس ورڈ ایک بار پھر درج کریں',
  ENTER_YOUR_NEW_PASSWORD: 'اپنا نیا پاس ورڈ درج کریں',
  NAME: 'نام',
  WHATSAPP: 'واٹس ایپ',
  SAVE_CHANGES: 'تبدیلیاں محفوظ کریں',
  ALL_TRIP: 'تمام سفر',

  ENTER_YOUR_WHATSAPP: 'اپنا واٹس ایپ درج کریں۔',

  CALCULATING_DISTANCE: 'فاصلہ حساب کیا جا رہا ہے',
  FETCHING_ROUTE: 'راستہ حاصل کیا جا رہا ہے',
  NO_INCOMPLETE_TRIPS: 'کوئی نامکمل سفر نہیں ملا',
  ALL_TRIPS_ARE_IN_PROGRESS: 'تمام دورے جاری ہیں۔',

  INCOMPLETE: 'نامکمل',
  ICOMPLETE: 'مکمل',
  IN_PROGRESS: 'جاری ہے',
  PRESS_TO_OPEN_CANVAS: 'دستخط کینوس کھولنے کے لیے دبائیں',
  PROCESSING: 'عمل جاری ہے...',
  CLEAR: 'صاف کریں',

  CONTINUE: 'جاری رکھیں',
  CLOSE: 'بند',
  COMPLETE: 'مکمل',

  NO_TRIP_PICKUP_FOUND: 'کوئی پک اپ ٹرپ نہیں ملا',

  LITRE: 'لیٹر',

  DAILY: 'روزانہ',
  WEEKLY: 'ہفتہ وار',
  URGENT: 'ہنگامی',
  WEEKLY_TRIP_LIST: 'ہفتہ وار سفر کی فہرست',

  NAVIGATE_ALL: 'سب پر نیویگیٹ کریں',
  DROP_OFF_OIL_CAN: 'تیل کا ڈبہ چھوڑیں',
  CANCEL_TRIP: 'سفر منسوخ کریں',
  SEARCH_SCHEDULES: 'شیڈول تلاش کریں',

  FUTUTRE_PICKUPS: 'مستقبل کے پک اپس',

  TODAY: 'آج',

  INVALID_EMAIL_ADDRESS: "غلط ای میل ایڈریس",


  CAPTURE: "Capture",
  UPLOAD: "Upload",

  "UPLOAD_IMAGE_VIDEO": "تصویر / ویڈیو اپ لوڈ کریں",
  "UPLOAD_VIDEO": "ویڈیوز اپ لوڈ کریں",
  "CANS": "ڈبے",
  "VIDEO_FRONT_BRANCH_DOOR": "فرنٹ برانچ فلور کی ویڈیو اپ لوڈ کریں۔",
  "ENTER_YOUR_NAME": "اپنا نام درج کریں",
  "NO_BRANCH_NAME": "کوئی برانچ نام نہیں"
}
